### ISSUE TITLE
The option Reformat only changed code(only if VCS configured) is not working

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#114]
From https://plugins.jetbrains.com/plugin/7642-save-actions

The option Reformat only changed code(only if VCS configured) is not working. Here is information of my environment. IntelliJ IDEA 2017.2.5 Build #IU-172.4343.14, built on September 26, 2017 JRE: 1.8.0_152-release-915-b12 amd64 JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o Linux 4.4.0-97-generic

**Comment by Maros-1984** [comment]
Same here. It happens only _sometimes_. It is usually enough to edit and save file line 2-5 times and the whole file would be reformatted (instead of the edited line) making the feature useless.

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by Delfic** [comment]
What is exactly the problem?

We had some people think it was not working when there was no such problem: We had some save-actions that changed non-changed code, making it into changed code and then reformatting it. The clarification that may be required is that reformatting is a single action (CTRL+ALT+L on Windows).

Now I am having what I believe is an actual issue. The following code is commited.
`/**
* Some Java-doc
*
* @throws ExceptionA
**/
private void method() throws ExceptionA;`
I make some changes in the method making it throw another exception and it makes sense to refer to another class `ClassA` having:
`/**
* Some Java-doc
*
* @throws ExceptionA
* @see ClassA
* @throws ExceptionB
**/
private void method() throws ExceptionA, ExceptionB;`

My configuration makes it that reformatting this code I get:
`/**
* Some Java-doc
*
* @throws ExceptionA
* @throws ExceptionB
* @see ClassA
**/
private void method() throws ExceptionA, ExceptionB;`

Alas, this formatting does not occur when i have the "Only VCS" option turned on. When those 2 lines are marked as new (or changed) they will not switch places.

**Comment by Maros-1984** [comment]
It sounds weird, but to simulate the issue I have to:
0. Have some lines formatted ugly and committed in VCS.
1. Format another line ugly.
2. **Quickly** save the file.

If I do save **immediatelly** after making an ugly change, the whole file is reformatted instead of the VCS-changed lines only (the bug). If I save the file _couple of seconds after_ making an ugly change, only the ugly formatted line is reformatted (so it works in this case). 

I fixed the issue in my fork, but I didn't care about the users who want to reformat the whole file, so I don't know if that still works. For the projects I am working on, reformatting the whole file isn't acceptable, by the rest of contributors. The pull request therefore probably shouldn't be accepted, but it may point you to the correct fix. The pull request also doesn't reformat anything when I save quickly, which is fine for me. For me, it is much worse to revert the whole file (except my changes), than have one line not formatted. So I am happy with my forked version. Thanks.

**Comment by Maros-1984** [comment]
@Delfic, on the second thought, my pull request doesn't break the Reformat whole file feature. So it should be fine in your scenario as well.

**Comment by dubreuia** [comment]
@Maros-1984 I responded on your PR, I didn't understand what you where trying to do, but re-reading this I understand. 

I'm ok with removing the if branch like you did in the PR if it fixes your problem. I just have to check if the behavior is ok for non CVS users, and maybe fix the UI if I can.

I'm in vacation right now but I'll merge beginning of next month. 

Thanks a lot for the PR, I really appreciate it

**Comment by dubreuia** [comment]
Merged.

It changes the current behavior (when selected, option "reformat only changed lines" used to reformat lines even if no VCS where configured, that is not the case anymore), but it's okay if it corrects a bug.
