### ISSUE TITLE
Only perform action if they are on the current file

### ISSUE THREAD

**Issue by quilicicf** [dubreuia/intellij-plugin-save-actions#119]
Hi, 

We are have been using the save action plugin for a while in our team and noticed a behavior that we think is not ideal. 
When using IntelliJ's reformatting capabilities, the save actions are applied on all impacted files. 

This means that when we change the name of a method, we potentially have `final` keywords added in hundreds of files which ruins the pull request. 

We thought maybe the save actions should be performed only in the current file.  

WDYT ?

**Comment by dubreuia** [comment]
Hey @quilicicf, thank you for your interest in the plugin.

First thought on your project: your formatting / code style is not correctly applied everywhere, you should reformat all files first, then use the plugin.

Concerning save-actions: the way it works is intellij keeps a list of "dirty" files, that are the files you have modified, but not yet written to disk. Those files go though save-actions. I suppose this is what you mean by "all impacted files". So if you don't modify a file, it doesn't goes though the save-actions plugin.

> This means that when we change the name of a method, we potentially have final keywords added in hundreds of files which ruins the pull request.

Yes, this is the intended behavior (minus the "ruins" part)

We could add a "apply only on focused file", but I don't think it is a good idea, since the save is async, the "focused file" loses meaning.

We could add a "add final keywords only on modified code" (this is available for the reformat code option), but I'm not sure it really cover you use case. This was asked early in issue #35 and was voted multiple times, but the implementation is difficult and never got the time to implement it.

I think you should review your usage of the plugin first: save-actions was designed to keep a tidy code base clean, not to cleanup a code base. Maybe you should deactivate some options?

I'm always open to PR and enhancements if you want to submit one (like implement #35 for example)

**Comment by quilicicf** [comment]
Well, we are working on an old code base that had never been even formatted before so we didn't want to bulk-change anything. 
Plus reformatting everything should be done when no-one has an open development or there are craploads of merge conflicts, and that just never happens so we are stuck with progressive reformatting.

I'll try to get a look at the code but I can't promise anything, I've never worked on an IntelliJ plugin before.

**Comment by dubreuia** [comment]
Hey @quilicicf,

I want to implement something that might be useful for your use case, it's #59, especially "Don't reformat any file on next save". That means you could (1) deactivate plugin on next save with a button (2) do refactoring change method name (3) the plugin won't do anything and reactivates by itself.

I need that feature so I'll develop it at some point, I though it might help you too.

**Comment by quilicicf** [comment]
That could help indeed!

**Comment by dubreuia** [comment]
Version 0.24 adds toggle support https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.24

I used it yesterday

- Deactivate save-actions with toggle "CTRL + SHIFT + A > Search 'Enable save-actions'"
- Do refactoring
- Re-activate save-actions with toggle

You can also bind the activation / deactivation to a key, see https://github.com/dubreuia/intellij-plugin-save-actions#keymap-and-actions

**Comment by quilicicf** [comment]
Awesome thanks!
Only little caveat when using the shortcut: there's no visual cue that it's done anything. 
Any way of doing that ? (if it's possible and I guess it'll be, I can contribute)

**Comment by markiewb** [comment]
> Any way of doing that ? (if it's possible and I guess it'll be, I can contribute)

Add Notifications to https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/src/com/dubreuia/core/SaveActionToggleAction.java

The doc is here https://www.jetbrains.org/intellij/sdk/docs/user_interface_components/notifications.html

**Comment by dubreuia** [comment]
Actually @quilicicf there is a visual cue, check out the "On / Off" on the right side of that screenshot. You can also add a notification if you'd like. I'd prefer an icon like the scala plugin (see #59) but I don't know how to do that 

![intellij-save-actions-plugin-actions](https://user-images.githubusercontent.com/657731/33232035-8025fbc6-d1ff-11e7-81cb-57ee044bc732.png)

**Comment by dubreuia** [comment]
Added screenshots in #59 for what I'd like

**Comment by quilicicf** [comment]
Actually, I've assigned a shortcut to `Enable save actions` directly. 
![selection_010](https://user-images.githubusercontent.com/5594303/33263075-c06103a6-d368-11e7-89ef-e7cf6196b7eb.png)
When I'm using it, nothing shows on-screen. I have to open the action pop-up (your screen above) to confirm I have deactivated the plugin. 

I'll try to have a look at how to add the icon like the scala plugin. I find it appealing too :-)

**Comment by dubreuia** [comment]
Oh I see. Yes in that case having a visual feedback makes sense.

For future reference, the scala plugin code where the button instanciation takes place is there: https://github.com/JetBrains/intellij-scala/blob/9198f8fb5b93d2ff142a65e320b812fc92cc0830/scala/scala-impl/src/org/jetbrains/plugins/scala/components/HighlightingAdvisor.scala

**Comment by quilicicf** [comment]
Cool I'll have a look at that thanks!
