### ISSUE TITLE
Plugin killed by IntelliJ autosave

### ISSUE THREAD

**Issue by dhafirnz** [dubreuia/intellij-plugin-save-actions#12]
I like this plugin but had to disable it because it was slowing down my IntelliJ. This is caused by the annoying auto save feature of IntelliJ. As a result, the SaveActions is invoked too often rendering the editor unusable because of the frequent pauses while it's doing it's thing. I don't think this is the plug-ins problem in this case, but I  am wondering if there is a trick to solve this?

**Comment by krasa** [comment]
File | Settings | Appearance & Behavior | System Settings   
do you have saving after 1 sec, as me?

**Comment by dhafirnz** [comment]
Most likely, I don't really know how often it saves but the moment I enabled the plug-in I started to slow and pause each time I hit the key board.

**Comment by dubreuia** [comment]
Hey I saw your comment on stack overflow, thanks for mentioning the problem.

You could deactivate the autosave feature in "File > Settings > Appearance & Behavior > System Settings > Save file on frame deactivation | Save automatically". You'll be back on a Eclipse-like save with CTRL-S. The plugin will still activate.

It might also be related to https://github.com/dubreuia/intellij-plugin-save-actions/issues/2.

The problem is that I cannot reproduce. Could you post OS / Intellij version please ?

**Comment by dorkbox** [comment]
@krasa The issue with saving ~1 second or so is because of "Make project automatically". Disable that, and the auto-save settings will operate as expected.

Please see this as well: https://youtrack.jetbrains.com/issue/IDEA-141128

**Comment by dhafirnz** [comment]
@dubreuia Thanks for your reply. OS Windows 7, IntelliJ 14.1.3.
The above setting won't stop auto-save. These are just if you deactivate the frame. I disabled them and can still see it auto saving regardless.
I even posted a question to IntelliJ support team and they said you cannot disable auto-saving.

**Comment by dubreuia** [comment]
Corrected in 0.5
