### ISSUE TITLE
Changes to multiple files, then Saving All causes multiple Rebuild tasks

### ISSUE THREAD

**Issue by deevodavis71** [dubreuia/intellij-plugin-save-actions#128]
Let me start by saying I love this plugin as it's a massive time saver.

However one thing I've noticed in my project is that when I have "Compile file" checked in the Save Action plugin configuration it causes a Rebuild task for each file that has changed.

In "normal" development usage (i.e. making changes to a file, saving it, moving to a new file to continue work) this isn't an issue. It causes an issue however when you trigger an action that causes changes to multiple files.

One example of this that I have just encountered is where I had to refactor multiple files (approx. 18) to change the name of a constant, and then clicked the "Save All" button on the toolbar.

This action caused 18 rebuild tasks to be created (along with a whole load of Sonarlint tasks) which obviously took a lot longer than it would have done for just a single one. To compound the issue further, the outcome of it all was that Intellij showed that the compilation had failed even though it was OK (because we use MapStruct and that uses an annotation processor that builds generated sources, and somewhere along the line the generated sources folder had been cleaned) but that's an aside. 

Performing a manual "Rebuild Project" after all the tasks had completed worked correctly with no errors.

For this reason I've now turned off the "Compile file" option for the time being but would love to be able to switch it back on again.

I appreciate that it's a tricky one but would it be possible for the plugin to detect that a build is in progress and not kick off a new one, or to delay a rebuild for a set time, or to wait until all tasks have completed and then show the user a dialog allowing them to kick off a new rebuild?

**Comment by dubreuia** [comment]
Hey @deevodavis71, thank you for your interest in the plugin. I actually stopped using this feature personally because of this issue, and though I should remove it, but finally kept it thinking maybe people still use it.

This one is not easy since the plugin triggers per-file. We can detect if a build is currently happening, but we won't know what to do with the other save events incoming. If we ignore them, some file might not be compiled (depends on class dependency graph, from what I understand, it will compile the file + dependent files).

We might be using the API wrong, there are other methods we could use, by giving a scope instead of files like

- `com.intellij.openapi.compiler.CompilerManager#compile(com.intellij.openapi.compiler.CompileScope, com.intellij.openapi.compiler.CompileStatusNotification)`
- `com.intellij.openapi.compiler.CompilerManager#make(com.intellij.openapi.compiler.CompileStatusNotification)`

The ideal flow would be (1) all save-actions events are processed but we do not build (2) on the last event, launch "build all". I don't know if that is possible. 

I probably won't have time to implement that anytime soon, but you can submit a PR anytime.

**Comment by deevodavis71** [comment]
Thanks for your response Alexandre. I didn't think it would be an easy one... 

I've just been tinkering with the Intellij keymap and found that if I remap CMD-S (on my Mac) from its original "Save All" to be "Rebuild Project" then it first saves all modified files and then starts a rebuild of the project. 

On my test project here at home it seems  to be quite workable but will have to see on Monday how much of a delay it might incur on my much larger project at work. 

Thanks again.

**Comment by dubreuia** [comment]
Yeah, "Rebuild project" will trigger save-actions.

I just don't like the idea of having to press keys, it's not what we're trying to achieve with save-actions. Also, you'll probably be impacted by #39, save might occur after the build (so if save-actions cleanup erroneous imports, the build will still fail because it will occur before the cleanup)

**Comment by dubreuia** [comment]
Fixed by #207

**Comment by dubreuia** [comment]
Released in https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.3.0
