### ISSUE TITLE
Prettier (or other terminal tool) support

### ISSUE THREAD

**Issue by martijnsenden** [dubreuia/intellij-plugin-save-actions#131]
This is more of a feature request. It would be amazing if this plugin would support performing a command line command hooked to the save action.

I currently use File Watchers to help perform changes with [Prettier](https://github.com/prettier/prettier). I know Webstorm supports file watchers, but these are not just triggered when saving the current file, they are also triggered when files are changed by e.g. changing branches or pulling from upstream. I do not want Prettier to always run when I get changes from elsewhere. I only want it to run on files for which I made changes that I saved.

Your tool could help me do just that if I could hook a command line command to the save event.

**Comment by dubreuia** [comment]
Hey @martijnsenden,

This feature has been asked multiple times, see #118 for the most recent proposal. My stance on this: I'm not going to call a random command line command from save-actions, since save-actions settings are commited, this is an open door to remote code execution.

But I'm willing to add an action "Run external tool by id", then save-actions could run the external(s) tool(s). External tools are configured in Intellij settings

I won't have time to develop this, but you can submit a PR anytime.

Check issue #118 for code snippets on how to do it

**Comment by dubreuia** [comment]
Duplicates #118

**Comment by im-martijn** [comment]
I don't have a Java build environment set up. I'm afraid I'll have to wait for someone to create the PR. I'm a frontend dev and I'm sure others would fix this better and quicker than I ever could.

**Comment by martijnsenden** [comment]
I don't have a Java build environment set up. I'm afraid I'll have to wait for someone to create the PR. I'm a frontend dev and I'm sure others would fix this better and quicker than I ever could.
