### ISSUE TITLE
Allow to  "Run Update Copyright..." on saved files

### ISSUE THREAD

**Issue by tandr** [dubreuia/intellij-plugin-save-actions#150]
When I save files, I would like copyright statement be updated according to rules I specify in "Update Copyright" preference. This item is available under Code->Update Copyright...

**Comment by dubreuia** [comment]
Hey @tandr. I really like the idea of having a "update copyright" save action. 

I checked how we could implement this:

- Use `com.maddyhome.idea.copyright.actions.UpdateCopyrightAction`
- Use `com.maddyhome.idea.copyright.actions.UpdateCopyrightProcessor`

I think the second option is better, since it would work like other processor we're using, like `com.dubreuia.processors.OptimizeImportsProcessor`. We could instanciate it there `com.dubreuia.processors.ProcessorFactory`, making it available for all Jetbrain's product.

I'm not sure I'll have time to develop that, but you can submit a PR anytime, anything you need to know for contributing is here https://github.com/dubreuia/intellij-plugin-save-actions#contributing

**Comment by tandr** [comment]
IntelliJ has an embedded action https://www.jetbrains.com/help/idea/generating-and-updating-copyright-notice.html (the same as organize imports etc). I don't remember installing a special plugin for it.

Would it be possible to run actions somehow by just selecting something from dynamic checklist box of ALL available refactors/code issue finders instead of  having a limited predefined list of actions?

**Comment by dubreuia** [comment]
Executing any IDE action was submitted as an improvement a while ago, see #118. 

IMO this issue is doable in a short amount of time, but implementing #118 is really a lot of work.

**Comment by tandr** [comment]
I will be happy with having at least copyright updated if it is possible to have it sooner :)

**Comment by rw00** [comment]
@dubreuia I couldn't find the library `com.maddyhome.idea.*` in the classpath
Where did you get those classes?

**Comment by rw00** [comment]
There are many more missing classes including one called `com.intellij.copyright.CopyrightManager` which is, I guess, part of the updated SDK (not found in 2016.3). 
Therefore, first we need to update the SDK then rely on the code you mentioned above

**Comment by dubreuia** [comment]
Too bad. I suppose copying the whole package `com.maddyhome.idea.copyright` is a bit too dirty: https://github.com/JetBrains/intellij-community/tree/0e91550e746c94ab6afe5c0d36450b93b587dd2d/plugins/copyright/src/com/maddyhome/idea/copyright

Doing a multi release jar is a lot of work for just this processor. I'm not against it since I feel we'll have to do it at some point, but this particular processor just isn't worth it IMO.

**Comment by dubreuia** [comment]
I'm working on #118 right now that might be used for that. Reopen if not enough

**Comment by matusfaro** [comment]
@dubreuia It cannot be used well for two reasons:
- There isn't a quick list action to update copyright to current file, only to the project so the dialog pops up asking which files to update copyright for (See screenshot below)
- Quick list items cannot be checked into repository, they are not project specific settings

![image](https://github.com/dubreuia/intellij-plugin-save-actions/assets/4206738/ce20b3ed-b8d2-4e8d-9bcb-c368882cc961)
