### ISSUE TITLE
Reformatting only changed code does not work in 1.4 and latest Intellij

### ISSUE THREAD

**Issue by xunnanxu** [dubreuia/intellij-plugin-save-actions#230]
**Describe the bug**
https://github.com/dubreuia/intellij-plugin-save-actions/issues/217 mentions reformatting only changed code option should work. However, it doesn't. In latest version of intellij it still modifies the entire file.

**To Reproduce**
1. Open an existing file with VCS enabled (e.g. git) that requires re-formatting in various places.
2. Change a line that triggers save action to fix it (e.g. requiring re-formatting)
3. Save the file
4. The entire file is modified

**Expected behavior**
Only that line should be reformatted.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1372575/54165427-dcc2b900-441d-11e9-9cec-311c4984e9d9.png)

**Versions**
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

Plugin version: 1.4

**Attachments**
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="noActionIfCompileErrors" />
        <option value="organizeImports" />
        <option value="reformatChangedCode" />
        <option value="fieldCanBeFinal" />
        <option value="localCanBeFinal" />
        <option value="missingOverrideAnnotation" />
        <option value="useBlocks" />
      </set>
    </option>
    <option name="configurationPath" value="" />
  </component>
</project>
```

**Comment by awelm** [comment]
+1, I am also having this issue

**Comment by dubreuia** [comment]
Hey @awelm and @xunnanxu can you define step number 3 in "To Reproduce"? How do you trigger save-actions?
- Frame deactivation (window loses focus)
- Shortcut
- ...

**Comment by xunnanxu** [comment]
@dubreuia frame deactivation/save all action

**Comment by jcBeaupre** [comment]
+1

I go into a file and change a single line and the whole file gets reformatted. I have to disable this plugin for now.

Worked well but stopped all of a sudden. I updated IntelliJ and save actions with no luck.

Anyone was able to find a fix?

```
IntelliJ IDEA 2018.3.6 (Community Edition)
Build #IC-183.6156.11, built on March 25, 2019
JRE: 1.8.0_152-release-1343-b28 X86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Save Actions: v1.5.0+2018.3

macOS Mojave 10.14.3
```

Settings.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="organizeImports" />
        <option value="reformatChangedCode" />
        <option value="fieldCanBeFinal" />
        <option value="localCanBeFinal" />
        <option value="missingOverrideAnnotation" />
        <option value="useBlocks" />
        <option value="unnecessarySemicolon" />
      </set>
    </option>
    <option name="configurationPath" value="" />
  </component>
</project>
```

**Comment by dubreuia** [comment]
It is really hard to fix since I can't reproduce. I'm pretty sure it has to do with the recent refactoring, but I have no idea why that happens.

**Comment by michal-liszewski** [comment]
Same thing happens to me after updating to 2018.3.6

**Comment by brunaguize** [comment]
I'm also experiencing the same bug on 2019.1.3 (Ultimate Edition)

**Comment by DragonAssassin** [comment]
If I am not mistaken, I believe underlying issue is related to how [Java Fixes](https://github.com/dubreuia/intellij-plugin-save-actions#java-fixes) operate when using the option to reformat only changed changed code. I would assume that the java fixes are only applied to changed code when the option is selected. This does not appear to be what is happening. To demonstrate the issue, here is some code that has many formatting problems.

```java
package issues;

import java.util.Set;
import java.util.List;
import java.util.Collection;

public class SaveAction230 {
	public static void main(String[] args) {
		int x = 0;;

        System.out.println(x);

		Set<String> s;
	    Collection<String> c;
	}
}
```

I ran a few experiments by adding `int y = 0;` on line 10. Then I saved the file.

1. Test reformat only changed code
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="reformatChangedCode" />
      </set>
    </option>
    <option name="configurationPath" value="" />
  </component>
</project>
```
```diff
diff --git a/src/issues/SaveAction230.java b/src/issues/SaveAction230.java
index 0182199..d611f91 100644
--- a/src/issues/SaveAction230.java
+++ b/src/issues/SaveAction230.java
@@ -7,6 +7,7 @@ import java.util.Collection;
 public class SaveAction230 {
 	public static void main(String[] args) {
 		int x = 0;;
+		int y = 0;
 
         System.out.println(x);
```

This appears to be working as expected.

2. Verify that reformat all lines works as expected to make sure that other issues are detected.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="reformat" />
      </set>
    </option>
    <option name="configurationPath" value="" />
  </component>
</project>
```
```diff
diff --git a/src/issues/SaveAction230.java b/src/issues/SaveAction230.java
index 0182199..1211ff9 100644
--- a/src/issues/SaveAction230.java
+++ b/src/issues/SaveAction230.java
@@ -6,11 +6,13 @@ import java.util.Collection;
 
 public class SaveAction230 {
 	public static void main(String[] args) {
-		int x = 0;;
+		int x = 0;
+		;
+		int y = 0;
 
-        System.out.println(x);
+		System.out.println(x);
 
 		Set<String> s;
-	    Collection<String> c;
+		Collection<String> c;
 	}
 }
```

This appears to work as well.

3. Test reformat only changed code in combination with remove unnecessary semicolons.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="reformatChangedCode" />
        <option value="unnecessarySemicolon" />
      </set>
    </option>
    <option name="configurationPath" value="" />
  </component>
</project>
```
```diff
diff --git a/src/issues/SaveAction230.java b/src/issues/SaveAction230.java
index 0182199..6aa1311 100644
--- a/src/issues/SaveAction230.java
+++ b/src/issues/SaveAction230.java
@@ -6,7 +6,8 @@ import java.util.Collection;
 
 public class SaveAction230 {
 	public static void main(String[] args) {
-		int x = 0;;
+		int x = 0;
+		int y = 0;
 
         System.out.println(x);
```

This does not work as I would expect as it fixes line 9 which was not changed by this edit. I also tried making the change below the print statement to make sure that I was not accidentally editing line 9. However, line 9 was still reformatted to drop the unnecessary semicolon.

On a side note, it appears that when Optimize Imports is enabled it will also optimize imports even when reformat only changed code is enabled. I assume that this is by design though. But could also be a reason a file changes when you did not directly edit that portion.

Versions:
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 28, 2019
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Save Actions: 1.6.0+2018.3

**Comment by dubreuia** [comment]
Hello @DragonAssassin, thank you for the debugging! You can confusing two different things: "reformating" and "quick fixes". Reformatting has an option to work on changed line only, but no other action has that functionality. Quick fixes always apply to all the lines. 

I thought of implementing the "Action on changed code", but it is a lot of work, and honestly, I'm not sure applying the modification to only changed lines is a good practice, but kept it because people kept asking for it.
