### ISSUE TITLE
Specify maximum supported platform version for v1.5.0

### ISSUE THREAD

**Issue by kedar-joshi** [dubreuia/intellij-plugin-save-actions#261]
**Describe the bug**
Plugin `v1.5.0` currently has open ended maximum supported version. Due to various changes in IntellIJ `2019.3`, current version can't be supported beyond 2019.2.* and same should be made explicit to avoid plugin accidentally getting updated on supported platform.

See -

```xml
<idea-version since-build="191"/> <!-- no until-build -->
```

**Comment by dubreuia** [comment]
Hello, thank you for this issue.

Unfortunately we won't be doing this because I would need to release a new version of the plugin for each version of Intellij, meaning I would need to test every version myself. I don't have that kind of time. By leaving the version open, the plugin gets crowd tested. It is also on par with what I've seen on other plugin projects.

Concerning the annotation, I'm pretty sure we can just add it and backport the changes in all branches and versions.

**Comment by kedar-joshi** [comment]
> ... By leaving the version open, the plugin gets crowd tested. 

Understood.

> Concerning the annotation, I'm pretty sure we can just add it and backport the changes in all branches and versions.

If you are referring to annotation changes for `@NonInjectable` then these can't be backported as the annotation is only available for platform `v2019.3+`.

**Comment by dubreuia** [comment]
> If you are referring to annotation changes for @NonInjectable then these can't be backported as the annotation is only available for platform v2019.3+.

This is awful
