### ISSUE TITLE
I wish that Save Actions setting is applied to for every project not specific project

### ISSUE THREAD

**Issue by hihiboss** [dubreuia/intellij-plugin-save-actions#336]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/34789831/93423043-00f33600-f8f0-11ea-8b4e-a87d7b7de34e.png)
Save Actions is able to configured to each project. So, if I do something for several projects, I should configure each project.
I wish that Save Actions setting are applied to global setting! Then, I'll have no needs to configure Save Actions setting to all projects! 

**For what product**

Intellij but this could be applied to all products :)

**Comment by dubreuia** [comment]
Hey @hihiboss,

Thank you for your interest in the plugin. This issue has been proposed before (see #305 for discussion), but I decided against it (the workaround is to the configure "New projects" in Intellij so that all of your new projects in Intellij have the same config when they are created).

I've decided against it because some user also want the opposite: project configuration (not global). See this original issue from 2017: #68. 

There was a tentative pull request to have both at the same time: #251, but the code and resulting UI was convoluted. Pull requests welcome, but we need to keep both functionalities (project and global)

**Comment by hihiboss** [comment]
Thank you for your kind explaination! 

I understand your thought and decision. I agree with those. =)

And, I really thank you for your awesome plugin. My development life has been turned to more comfortable and cool. 

I’m expecting and pulling for yours. 👍

**Comment by dubreuia** [comment]
Positive feedback like this makes my day, thanks :smile:
