### ISSUE TITLE
Add "only change lines" to inspections

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#35]
Add the option for each one individually. 

It should have the same mechanism than #34.

**Comment by dubreuia** [comment]
WNF

**Comment by Robrowski** [comment]
Can this be reconsidered? The inclusions/exclusions is going to help me get by for a while, but ultimately I will have to stop using the plugin altogether without a feature like this. The inspections end up being far too disruptive for my team's code review process.

**Comment by dubreuia** [comment]
Sure! I'm reopening.

I'll be honest thought this is a big development and it's not priority since it's very specific (lot's of bugs to correct before that). I'm not seing this done anytime soon without help from a PR.

**Comment by aalosious** [comment]
+1 on the enhancement.. The Eclipse "Save Actions" already supports this.

Below is why this would be a big enhancement for my use case:
I often keep manual formatting to enhance readability and uncluttering (like adding newlines where the auto-formatter wouldn't). Right now, I have to worry about the plugin undoing my uncommitted formatting changes. So, I have to either untick the "Reformat file" option in the plugin or commit my changes to git before continuing. This limits the use of the plugin for me. So, if the plugin could diff with the last saved state of the file (rather than the last git committed version of the file) before formatting, it would be great.

Thanks for the effort, dubreuia.

**Comment by dubreuia** [comment]
Hello @aalosious, I'm not sure this plugin fits your use case: you either have a formatter that fits your usage and save-actions applies it automatically, or you don't use auto-something at all and do everything by hand.

For some files you might want to temporarily stop auto-formatting (like: "don't reformat this file on next save") and that development is in #59

**Comment by dubreuia** [comment]
Moved to "ideas"
