### ISSUE TITLE
Allow for custom save actions for specific files

### ISSUE THREAD

**Issue by stevenroose** [dubreuia/intellij-plugin-save-actions#61]

**Comment by ArchieT** [comment]
Yeah, such as _Code » Reformat with Dart style_ for Dart files

**Comment by stevenroose** [comment]
Or `go fmt` for Go :)

**Comment by ArchieT** [comment]
Yeah, forgot gofmt is also separate from simple Reformat in IntelliJ.

**Comment by dubreuia** [comment]
So it would be some kind of action file mask? Apply "Reformat" on *.java but not *.xml.

The dart thing is a separate issue, to add a new reformat action which is available if you have dart language support.

**Comment by stevenroose** [comment]
The issue with Go is that the plugin does not follow the community-accepted
format so a lot of us want a way to add a real `go fmt ./...` at save time
instead of just checking the box "reformat".

**Comment by studgeek** [comment]
As a first step, if the plugin at just supported run script option for all files, then the script itself could conditionally take action based on the file.

**Comment by alexander-doroshko** [comment]
For Dart developers: since IntelliJ IDEA / WebStorm 2017.2 you may enable 'Use the dartfmt tool when formatting the whole file' option in Settings (Preferences) | Editor | Code Style | Dart | Dartfmt tab. It makes standard 'Reformat Code' action call `dartfmt` (aka Dart Style) tool instead of using IDE's own formatter. As a result 'Save Actions' plugin will cause `dartfmt` tool to work on save.

**Comment by dubreuia** [comment]
Yeah! This is good news.

**Comment by dubreuia** [comment]
Duplicates #72
