### ISSUE TITLE
[Build action] Add update resources on save in debug mode

### ISSUE THREAD

**Issue by xinkunZ** [dubreuia/intellij-plugin-save-actions#75]
IDEA will compile java files and make modules before run/debug，so we need not compile java file after save action every time.  I want to know if the [compile file] option can only work on debug model？ THX！

**Comment by dubreuia** [comment]
The idea behind the "compile on save" is that the projet is ready to go as soon as you hit "Run / Debug". 

Actually there was a "update resources on save" feature before that was very handy in debug mode, it would hot-reload the classes / resources (when possible) during your debug session. I removed it because it was not working properly, but I'd really like to add it again.

**Comment by xinkunZ** [comment]
OK,thanks! Another question is that if I'm editing code with IDEA setting [save files automactically... ... 5 sec ], also I select [complie file] and  [reformate file] options in save action, when I stop edit code, the synchronization will notify save action to compile and formate file, but actually I haven't finish my code, so compile and formate will bring some error, How can I avoid this situation if I don't close [save files automactically] option and set time like 500 sec or 1000 sec. Thank you very much!

**Comment by markiewb** [comment]
@xinkunZ: "...so compile and formate will bring some error..." See #76. Comment your issue there.

**Comment by dubreuia** [comment]
Add options so that while debugging, the plugin will:

- Reload classes
- Updates classes and resources

**Comment by dubreuia** [comment]
Fixed by #207

**Comment by dubreuia** [comment]
Released in https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.3.0
